name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

   # runs-on: ubuntu-latest
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
